<script setup>
// Future development:
//  Deal with two different timelines and representation, since timestamps are different in some cases
//  Hover on second data set

import Chart from "chart.js/auto";

import { onMounted } from "vue";

const props = defineProps({
  batch: String,
  sensor: String,
  description: String,
  unit: String,
  values: Object,
  timestamps: Object,

  secondBatch: String,
  secondSensor: String,
  secondDescription: String,
  secondUnit: String,
  secondValues: Object,
  secondTimestamps: Object,
});

// Charts autogenerated colors with alpha
const randomBackgroundColor = () => {
  const r = Math.floor(Math.random() * 255);
  const g = Math.floor(Math.random() * 255);
  const b = Math.floor(Math.random() * 255);
  return `rgba(${r}, ${g}, ${b}, 0.5)`;
};
let backgroundColorOneA05 = randomBackgroundColor();
let backgroundColorOneA1 = backgroundColorOneA05.replace("0.5", "1");
let backgroundColorTwoA05 = randomBackgroundColor();
let backgroundColorTwoA1 = backgroundColorTwoA05.replace("0.5", "1");

onMounted(() => {
  const ctx = document.getElementById("myChart");
  const myChart = new Chart(ctx, {
    type: "line",
    data: {
      labels: props.timestamps,
      datasets: [
        {
          label: `${props.batch} - ${props.sensor}`,
          data: props.values,

          backgroundColor: backgroundColorOneA05,
          fill: true,
          borderWidth: 0.1,
          borderColor: "white",
          tension: 0.5,
        },
        {
          label: `${props.secondBatch} - ${props.secondSensor}`,
          data: props.secondValues,

          backgroundColor: backgroundColorTwoA05,
          fill: true,
          borderWidth: 0.1,
          borderColor: "white",
          tension: 0.5,
        },
      ],
    },
    options: {
      scales: {
        y: {
          ticks: {
            callback: function (value, index, ticks) {
              return value + " " + props.unit;
            },
          },
          grid: {
            display: true,
          },
        },
        x: {
          ticks: {
            callback: function (value) {
              let fullBottomTick = this.getLabelForValue(value);
              let shortBottomTick = fullBottomTick.slice(10, 16);
              return shortBottomTick;
            },
          },
          grid: {
            display: false,
          },
        },
      },
      plugins: {
        legend: {
          display: true,
        },
        filter: {
          propogate: true,
        },
        tooltip: {
          callbacks: {
            label: function (context) {
              let label = context.dataset.label || "";
              if (label) {
                label += " / ";
              }
              if (context.parsed.y !== null) {
                label += context.parsed.y.toFixed(3) + " " + props.unit;
              }
              return label;
            },
          },
        },
      },
      responsive: true,
      radius: 2,
      hoverRadius: 8,
      hoverBackgroundColor: backgroundColorOneA1,
      hitRadius: 15,
    },
  });
});
</script>

<template>
  <div class="relative">
    <canvas
      class=""
      id="myChart"
      aria-label="Data Visualisation"
      role="img"
    ></canvas>
  </div>
</template>
