<script setup>
import Chart from 'chart.js/auto'

import { onMounted } from 'vue';

const props = defineProps({
    batch: String,
    sensor: String,
    description: String,
    unit: String,
    values: Object,
    timestamps: Object,
})

// Charts autogenerated colors with alpha
const randomBackgroundColor = () => {
    const r = Math.floor(Math.random() * 255);
    const g = Math.floor(Math.random() * 255);
    const b = Math.floor(Math.random() * 255);
    return `rgba(${r}, ${g}, ${b}, 0.5)`;
}
let backgroundColorA05 = randomBackgroundColor();
let backgroundColorA1 = backgroundColorA05.replace('0.5', '1');

onMounted(() => {    
    const ctx = document.getElementById('myChart');

    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: props.timestamps,
            datasets: [{  
                label: `${props.batch} - ${props.sensor}`,
                data: props.values,

                backgroundColor: backgroundColorA05,
                fill: true,
                borderWidth: 0.1,
                borderColor: 'white',
                tension: 0.5,
            },]
            // above goes other datasets for visualisation on the same chart
        },
        options: {
            scales: {
                y: {
                    ticks: {
                        callback: function(value, index, ticks) {
                            return value + ' ' + props.unit;
                        }
                    },
                    grid: {
                        display: false,
                    }
                },
                x: {
                    ticks: {
                        callback: function(value) {
                            let fullBottomTick = this.getLabelForValue(value)
                            let shortBottomTick = fullBottomTick.slice(10, 16)
                            return shortBottomTick;
                        }
                    },
                    grid: {
                        display: false,
                    }
                },
            },
            plugins: {
                legend: {
                    display: false
                },
                filter: {
                    propogate: true
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            let label = context.dataset.label || '';
                            if (label) {
                                label += ' / ';
                            }
                            if (context.parsed.y !== null) {
                                label += context.parsed.y.toFixed(3) + ' ' + props.unit;
                            }
                            return label;
                        }
                    }
                }
            },
            responsive: true,
            radius: 2,
            hoverRadius: 8,
            hoverBackgroundColor: backgroundColorA1,
            hitRadius: 15,
        }
    });
})
</script>

<template>

    <div class="relative">
        <canvas class="" id="myChart" aria-label="Data Visualisation" role="img"></canvas>
    </div>

</template> 

